### ISSUE TITLE
Sidebar display issue

### ISSUE THREAD

**Issue by lukstei** [patrickfav/website-favre#1]
![image](https://user-images.githubusercontent.com/292363/82052626-455d9380-96bc-11ea-98ad-696a105ef3a0.png)

**Comment by patrickfav** [comment]
First of all, please update your chrome!

Second, thanks for reporting, the problem here is, that this document just has too many headers and the used ToC widget can't handle this. I will see if this can easily be fixed, otherwise Ill probably simplify the content.

**Comment by lukstei** [comment]
Thanks for confirming - where can I find your bug bounty program policy? 
Who will contact me regarding the reward finding this critical bug?

**Comment by patrickfav** [comment]
The policy can be found [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ). I don't know the tiers at the back of my head, but I guess it is at least in the 4 digits range (EUR of course). An associate with Patrickfav Open Source Soft & Co will contact you shortly.
